services:
  zap:
    image: zaproxy/zap-stable
    container_name: zap
    user: zap
    restart: unless-stopped
    ports:
      - "${ZAP_PORT}:${ZAP_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: .env
        required: true
    volumes:
      - ./zap-data:/home/zap/.ZAP
      - ./zap-reports:/zap/reports
    command: [
      "zap.sh", 
      "-daemon", 
      "-host", "0.0.0.0", 
      "-port", "${ZAP_PORT}", 
      "-config", "api.addrs.addr.name=.*", 
      "-config", "api.addrs.addr.regex=true", 
      "-config", "api.key=${ZAP_API_KEY}",
      "-config", "network.localServers.aliases.alias.name=${EC2_PUBLIC_IP}",
      "-Xmx6g"
    ]